name: Node.js CI & CD

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # cache node modules
      - name: Cache node modules
        uses: actions/cache@v1
        id: node-modules-cache
        env:
          cache-name: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # install dependencies
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install
      
      # Lint
      - name: Lint
        run: npm run lint

      # Build
      - name: Build
        run: npm run build
      
      # Archive build dist artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist
      
      # Unit test
      - name: Unit test
        run: npm run test:unit
      
      # Archive coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
      
      # Build and upload test to code climate
      - name: Test & publish code coverage to code climate
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test:unit
          debug: true

      # github pages.
      - name: Build and deploy github pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist