name: GH Release

on:
  push:
    tags:
      - 'release-*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install

        # Generate change logs
      - name: Generate chagne logs
        run: npm run version

        # Archive change logs
      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
      
      # Added release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}