# work flow action will run when PR merged or push to master
name: Master Pushed

on:
  push:
    branches:
      - master
jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # cache node modules
      - name: Cache node modules
        uses: actions/cache@v1
        id: node-modules-cache
        env:
          cache-name: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ runner.os }}-build-${{ runner.os }}

      # install dependencies
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install

      # Lint
      - name: Lint
        run: npm run lint

      # Build
      - name: Build
        run: npm run build

      # Archive build dist artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

      - name: Unit Test
        run: npm run test:unit

      # Archive coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage

      # Upload test coverage to codecov
      - name: Upload test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
          name: tw-syncer
          fail_ci_if_error: true

      # Test & publish code coverage to code climate
      - name: Test & publish code coverage to code climate
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test:unit
          debug: true
